const shopActionType = {
  FETCH_STORE_ITEMS_START: "FETCH_STORE_ITEMS_START",
  FETCH_STORE_ITEMS_SUCCESS: "FETCH_STORE_ITEMS_SUCCESS",
  FETCH_STORE_ITEMS_ERROR: "FETCH_STORE_ITEMS_ERROR",
};

export default shopActionType;
